### ISSUE TITLE
Run linters in CI

### ISSUE THREAD

**Issue by jayvdb** [abuccts/enwiktionary2cmudict#3]
Since #2, there are now 3 errors from `pyflakes`, and 16 from `pycodestyle`.

Please fix and use continuous integration to prevent new code style problems being introduced.  I strongly recommend Travis CI for this purpose.

Many python projects also like to use `tox` to assist in running tests and linter tools locally, in which case `tox-travis` is a way to simplify using the same configuration for tox and travis.  If you are not familiar with tox already, I caution against learning & using tox in this project as it is 'over-kill'.

**Comment by abuccts** [comment]
`pylint` is used and I have added it in [Travis CI](https://github.com/abuccts/enwiktionary2cmudict/blob/master/.travis.yml)
