### ISSUE TITLE
Self-contained tests and CI

### ISSUE THREAD

**Issue by jayvdb** [abuccts/enwiktionary2cmudict#4]
Please add a self contained test suite, that is run in CI.
Currently `test.py` relies on a dump file being downloaded prior to running the tests, and placed in a specific directory.

```python
dump_file = "../enwiktionary-latest-pages-articles-multistream.xml"
```

I am guessing that is a very large download, which we do not want the CI server to fetch every time the tests are run.  Could you confirm the size?

It is better to add to the repository a set of small sample XML files that can be used to test specific problems, so tests run quickly.

**Comment by abuccts** [comment]
Added. Please refer to https://github.com/abuccts/enwiktionary2cmudict/tree/master/pywiktionary/data and https://travis-ci.org/abuccts/enwiktionary2cmudict.
